### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by JoshOOOOWAH** [mops1k/mcshop-v4#1]
При установке при помощи composer вылезает ошибка
` [RuntimeException]
  Failed to clone https://github.com/mops1k/StofDoctrineExtensionsBundle.git via https, ssh protocols, aborting.

  - https://github.com/mops1k/StofDoctrineExtensionsBundle.git
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/mops1k/StofDoctrineExtensionsBundle.git/'

  - git@github.com:mops1k/StofDoctrineExtensionsBundle.git
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
`
Предполагаю, что такого репозитория просто нет

**Comment by mops1k** [comment]
Да, компонент был удален...
